title: Lycheese's Blog
email: dev@lycheese.org
description: >-
  Description pending.
baseurl: ""
url: "https://blog.lycheese.org"
github_username:  lycheese

# Build settings
theme: null
plugins:
  - jekyll-feed

include: [_pages]

defaults:
  -
    scope:
      type: posts
      path: _posts
    values:
      isPost: true
      layout: post
      permalink: /posts/:categories/:title/
  -
    scope:
      type: pages
      path: _pages
    values:
      isPost: false
      layout: default
